name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 14.x


      # 安装前端依赖
      - name: Install frontend dependencies
        working-directory: ./front-end
        run: npm install

      # 安装后端依赖
      - name: Install backend dependencies
        working-directory: ./server
        run: npm install

      # 构建前端
      - name: Build frontend
        working-directory: ./front-end
        run: npm run build

      # 如果你有后端测试，可以在这里运行它们
      - name: Run backend tests (or other tasks)
        working-directory: ./server
        run: npm test

      # 启动前端
      - name: Start frontend
        working-directory: ./front-end
        run: npm run dev &

      # 启动后端
      - name: Start backend
        working-directory: ./server
        run: node app.js &
